version: "3.7"
services:
  infracloudio_csvserver:
    image: infracloudio/csvserver
    ports:
      - 9393:9300
    volumes:
      - ./inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange

  infracloudio_prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - /home/lenovo/infracloud/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
